### ISSUE TITLE
ConstraintLayout crash

### ISSUE THREAD

**Issue by paulkugaev** [Skyyo/ComposeExpandableList#1]
AnimatedVisibilty crashes if ExpandableContent is actually a ConstraintLayout

**Comment by Skyyo** [comment]
Are you sure this isn't a compose ConstraintLayout issue? Last time I was checking it, constraintLayout still did 2 layout passes, and wasn't ready yet for the compose. 
If you're seeking help - please provide a reproducible sample so I can look into it @paulkugaev

**Comment by paulkugaev** [comment]
I'm totally not sure. But I'll send you the sample today

**Comment by Skyyo** [comment]
any updates on this @paulkugaev ?
