### ISSUE TITLE
AnimatedVisibility no longer accepts initiallyVisible as a parameter

### ISSUE THREAD

**Issue by thoku1** [Skyyo/ComposeExpandableList#2]
Thank you for this really inspiring example.
I am struggling with the deprecation warning in fun ExpandableContent():

`'AnimatedVisibility(Boolean, Modifier = ..., EnterTransition, ExitTransition, Boolean, () -> Unit): Unit' is deprecated. AnimatedVisibility no longer accepts initiallyVisible as a parameter, please use AnimatedVisibility(MutableTransitionState, Modifier, ...) API instead`

Do you have a solution for this?

**Comment by Skyyo** [comment]
Thanks for kind words @thoku1 . Just updated the repo, please pull the latest changes. Should be no more deprecation warning. Feel free to reopen the issue in case I've missed something
